# Generated by Django 5.2.1 on 2025-05-30 09:00

import talks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='video_link',
            field=models.URLField(help_text='Link to the streaming'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='video_link',
            field=models.URLField(blank=True, default='', help_text='Link to talk recording. Overrides the calculated streaming link if provided.', validators=[talks.validators.validate_video_link]),
        ),
    ]
