# Generated by Django 5.2.3 on 2025-06-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_alter_streaming_video_link_alter_talk_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='video_start_time',
            field=models.PositiveIntegerField(blank=True, help_text='Start time in seconds', null=True),
        ),
    ]
