# Generated by Django 5.2.3 on 2025-07-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_question_questionvote_answer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='answer',
            new_name='talks_answe_questio_7b1874_idx',
            old_name='talks_answe_questio_77795a_idx',
        ),
        migrations.RenameIndex(
            model_name='answer',
            new_name='talks_answe_user_id_daf6f4_idx',
            old_name='talks_answe_user_id_bd34d2_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='talks_quest_talk_id_7ff30b_idx',
            old_name='talks_quest_talk_id_552c58_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='talks_quest_user_id_517935_idx',
            old_name='talks_quest_user_id_81381e_idx',
        ),
        migrations.RenameIndex(
            model_name='questionvote',
            new_name='talks_quest_questio_99a23f_idx',
            old_name='talks_quest_questio_5d98c1_idx',
        ),
        migrations.RenameIndex(
            model_name='questionvote',
            new_name='talks_quest_user_id_7900ca_idx',
            old_name='talks_quest_user_id_c0a17e_idx',
        ),
    ]
