# Generated by Django 5.2.3 on 2025-08-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_rename_talks_answe_questio_77795a_idx_talks_answe_questio_7b1874_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text="Whether to display the author's name - deprecated, always set to False"),
        ),
    ]
