# Generated by Django 5.2.5 on 2025-08-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0009_alter_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('answered', 'Answered'), ('rejected', 'Rejected')], default='approved', help_text='Status of the question', max_length=10),
        ),
    ]
