# Generated by Django 5.2.5 on 2025-11-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0010_alter_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('answered', 'Answered'), ('rejected', 'Rejected')], default='pending', help_text='Status of the question', max_length=10),
        ),
    ]
