# Generated by Django 5.2.5 on 2025-11-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0010_alter_talk_image_alter_talk_presentation_type'),
        ('talks', '0012_rating'),
    ]

    operations = [
    ]
