# Generated by Django 6.0.2 on 2026-02-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0014_talk_event_alter_talk_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, help_text='Optional comment about the talk (visible only to admins)', max_length=2000),
        ),
    ]
