# Generated by Django 6.0.2 on 2026-02-28 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0015_alter_rating_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this talk was saved')),
                ('talk', models.ForeignKey(help_text='The saved talk', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='talks.talk')),
                ('user', models.ForeignKey(help_text='The user who saved the talk', on_delete=django.db.models.deletion.CASCADE, related_name='saved_talks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Talk',
                'verbose_name_plural': 'Saved Talks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'talk'], name='talks_saved_user_id_a768c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'talk'), name='unique_user_saved_talk')],
            },
        ),
    ]
