# Generated by Django 6.0.4 on 2026-05-24 21:33

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_transcriptions_url'),
        ('talks', '0021_alter_talk_presentation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='end_time',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('start_time'), '+', models.F('duration')), help_text='Computed talk end time (start_time + duration). Managed by the database.', output_field=models.DateTimeField()),
        ),
        migrations.AddIndex(
            model_name='talk',
            index=models.Index(fields=['end_time'], name='talks_talk_end_tim_597175_idx'),
        ),
        migrations.AddIndex(
            model_name='talk',
            index=models.Index(fields=['room', 'end_time'], name='talks_talk_room_id_fb3124_idx'),
        ),
    ]
