# Generated by Django 6.0.4 on 2026-05-24 21:33
# Replaced GeneratedField with a regular column: PostgreSQL rejects timestamptz + interval
# in GENERATED ALWAYS AS because the + operator is STABLE, not IMMUTABLE.

from django.db import migrations, models


def backfill_end_time(apps, schema_editor):  # type: ignore[no-untyped-def]
    talk_model = apps.get_model("talks", "Talk")
    for talk in talk_model.objects.filter(end_time__isnull=True).iterator(chunk_size=500):
        talk.end_time = talk.start_time + talk.duration
        talk.save(update_fields=["end_time"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_transcriptions_url'),
        ('talks', '0021_alter_talk_presentation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='end_time',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Computed talk end time (start_time + duration). Never set directly.',
            ),
        ),
        migrations.RunPython(backfill_end_time, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='talk',
            index=models.Index(fields=['end_time'], name='talks_talk_end_tim_597175_idx'),
        ),
        migrations.AddIndex(
            model_name='talk',
            index=models.Index(fields=['room', 'end_time'], name='talks_talk_room_id_fb3124_idx'),
        ),
    ]
